name: Build and deploy Angular app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: PhoenixTheatre    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: './PhoenixTheatreAngular/dist'      # set this to the path to your web app project, defaults to the repository root

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**PhoenixTheatreAngular/src/index.html') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          pwd
          ls ./PhoenixTheatreAngular
            
#       - name: Build Angular
#         run: |
#           ng build

          
#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.AZURE_WEBAPP_APP_PUBLISH_PROFILE }}
#           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
